"""change questionlist to pickletype

Revision ID: 74a4234c0aff
Revises: 2fd93cbc8559
Create Date: 2020-12-18 11:16:42.615989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a4234c0aff'
down_revision = '2fd93cbc8559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'question_list',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.PickleType(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'question_list',
               existing_type=sa.PickleType(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
